### ISSUE TITLE
DMCs and DMRs of large numbers of biological replicates

### ISSUE THREAD

**Issue by CTLife** [al2na/methylKit#104]
MethylKit, is it appropriate for RRBS data with large numbers of biological replicates ?     
Such as 100 biological replicates of each group for detecting DMCs and DMRs.        
Or which method should I choose for large numbers of biological replicates ?

**Comment by alexg9010** [comment]
Dear @CTLife ,

We discussed this problem of how to deal with large datasets in the analysis of bisulfite sequencing data in our review article (https://doi.org/10.1016/j.jbiotec.2017.08.007). 

Since you are dealing with RRBS and not WGBS data, I think `methylKit` should be able to manage your 100 replicates.
If you face memory issues consider using the possibility to work with your data as [flat file database](https://bioconductor.org/packages/release/bioc/vignettes/methylKit/inst/doc/methylKit.html#22_reading_the_methylation_call_files_and_store_them_as_flat_file_database) which could slow down your workflow in speed (rather small difference), but makes sure your resources suffice.   

If you have any other questions consider checking out our [channels](https://github.com/al2na/methylKit#staying-up-to-date).

Best,
Alex
