### ISSUE TITLE
missing normalized values for a sample in normalizeCoverage?

### ISSUE THREAD

**Issue by lshepard2154** [al2na/methylKit#173]
Hello,

I am currently trying to understand why the values from one sample from `normalizeCoverage` is not changed after normalization (can't tell if this is a bug or not). Here is an example using the data from the vignette:
```
myobj=methRead(file.list,
               sample.id=list("test1","test2","ctrl1","ctrl2"),
               assembly="hg18",
               treatment=c(1,1,0,0),
               context="CpG"
)

filtered.myobj=filterByCoverage(myobj,lo.count=10,lo.perc=NULL,
                                hi.count=NULL,hi.perc=99.9)
filtered.myobj
```
`filtered.myobj[[1]]` shows 
```
methylRaw object with 1902 rows
--------------
    chr   start     end strand coverage numCs numTs
1 chr21 9764539 9764539      -       12     3     9
2 chr21 9764513 9764513      -       12     0    12
3 chr21 9820622 9820622      +       13     0    13
4 chr21 9837545 9837545      +       11     0    11
5 chr21 9849022 9849022      +      124    90    34
6 chr21 9853326 9853326      +       17    12     5
--------------
sample.id: test1 
assembly: hg18 
context: CpG 
resolution: base 
```
Now normalize it:
```
filtered.myobj <- normalizeCoverage(filtered.myobj)
filtered.myobj
```

and `filtered.myobj[[1]]` still shows:

```
methylRaw object with 1902 rows
--------------
    chr   start     end strand coverage numCs numTs
1 chr21 9764539 9764539      -       12     3     9
2 chr21 9764513 9764513      -       12     0    12
3 chr21 9820622 9820622      +       13     0    13
4 chr21 9837545 9837545      +       11     0    11
5 chr21 9849022 9849022      +      124    90    34
6 chr21 9853326 9853326      +       17    12     5
--------------
sample.id: test1 
assembly: hg18 
context: CpG 
resolution: base 
```

The other 3 samples in this particular case have different values after normalization. Is this expected behavior or a bug?

Thanks for the clarification!

Also, on another note. If one is combining the methylation across regions (tiles or using `regionCounts`, is it recommended to run the above normalization of the individual CpGs prior to `regionCounts` or after? I have done both ways, and while there are differences, it's not too large of a difference, but wanted to check if there is a specific guideline.

**Comment by alexg9010** [comment]
Hi @lshepard2154 ,

The coverage is normalised by multiplying with a scaling factor derived from the mean (or median ) of the coverage distributions see [here](https://github.com/al2na/methylKit/blob/master/R/normalizeCoverage.R#L82) . That means that the sample with the highest coverage will stay the same, while the other samples are scaled accordingly. 

To your second question, I think the normalisation should be done per base before summarising to regions. 
And as mentioned in the FAQ of the manual: 
"Ideally, you should first filter bases with extreme coverage to account for PCR bias using filterByCoverage() function, then run normalizeCoverage() function to normalize coverage between samples. These two functions will help reduce the bias in the statistical tests that might occur due to systematic over-sampling of reads in certain samples."

 I hope this helps.

Best,
Alex

**Comment by lshepard2154** [comment]
@alexg9010 thank you so much for this clarification. Very helpful! Truly appreciate it. I will close this issue now.
