### ISSUE TITLE
Output metDiff table with CpG and Gene annotations

### ISSUE THREAD

**Issue by Admera2020** [al2na/methylKit#205]
Hello,

I successfully ran methylkit with Gene and CpG annotations but struggling to find a way to generate an output file that contains values from methDiff and both the annotations. 

Is there a function for it that I am missing? 
 
Best
Nihir

**Comment by alexg9010** [comment]
Hi @Admera2020 ,

This question is probably more related to using the genomation package rather then methylKit, so @frenkiboy, @al2na and @katwre might be the right people to answer here. 

As far as I know, there is no single function to export these annotations since the usual endpoint would be to plot them. However you can access the internal data of the annotation objects with the `getAssociationWithTSS` or `getMembers` functions and then join them with the target methDiff data.frame, as they should have the same number of rows. 

I would do something like this:
```
# read the shores and flanking regions and name the flanks as shores
  # and CpG islands as CpGi
  cpg.obj=readFeatureFlank(fetched.cpgi,
                           feature.flank.name=c("CpGi","shores"))
  #
  # convert methylDiff object to GRanges and annotate
  diffCpGann=annotateWithFeatureFlank(target = GRanges.dmr,
                                      feature = cpg.obj$CpGi,
                                      flank = cpg.obj$shores,
                                      feature.name="CpGi",
                                      flank.name="shores",
                                      intersect.chr = TRUE)


  mcols(GRanges.dmr)[["CpGisland"]] <-  "other"
  GRanges.dmr$CpGisland[diffCpGann@members[,1] == 1] <- "CpGi"
  GRanges.dmr$CpGisland[diffCpGann@members[,2] == 1] <- "shore"

```

Best, 
Alex

**Comment by Admera2020** [comment]
Thank you Alex, sorry completely missed your response on this.
