### ISSUE TITLE
Meth.diff to fold-chage

### ISSUE THREAD

**Issue by sagarutturkar** [al2na/methylKit#211]
Is there any easy way to convert the `meth.diff` value to fold-change? How can I access the values used to calculate `meth.diff`?

If represented as fold-change, it would be a easy comparison with RNA-seq data.

**Comment by alexg9010** [comment]
Hi @sutturka,

I think there is no need to extract a fold-change from the meth.diff as
this value already tells you the direction and the amount of change. If
there is a correlation between changes in expression and methylation you
should be able to see them with meth.diff values already.

However, If you still want to get the fold change, the meth.diff value is
calculate as difference of the mean methylation values per group, so you
could extract these per base and then divide instead of subtracting them.

Best,
Alex



Sent from mobile.

sutturka <notifications@github.com> schrieb am Do., 22. Okt. 2020, 21:52:

**Comment by alexg9010** [comment]
Hi @sagarutturkar ,

Do you still need help with this, or can I close this issue?

**Comment by sagarutturkar** [comment]
Thank you for the quick response! This makes sense and I was able to get what needed.
