### ISSUE TITLE
Error in vapply(object, function(x) x@context, FUN.VALUE = "character")

### ISSUE THREAD

**Issue by hcph** [al2na/methylKit#245]
Hi, when I use the function of unite, the errors come:
$meth1 = unite(myobj1,destrand = F,suffix="BS-E",min.per.group=1L)
Error in vapply(object, function(x) x@context, FUN.VALUE = "character") : 
  values must be length 1,
 but FUN(X[[1]]) result is length 3
Could you please help me? By the way, thank you for developing this amazing tool.

**Comment by alexg9010** [comment]
Hi @HeChao7021, 

do you have a minimal reproducible code example that we can test?

**Comment by alexg9010** [comment]
Based on the error message, I would assume that the `context` field in one of your methylRaw objects is invalid.

**Comment by HeChao7021** [comment]
Oh, yes. I have set context=c("CpG","CHG","CHH") when using the methRead function, I will try to use one of the context soon. If still get issues, I will submit a minimal reproducible code example. Thank you very much!

**Comment by HeChao7021** [comment]
Hello, Alexander. The issue was fixed since I separately choose CpG at methRead stage. But I wonder whether if there were methods to analyze all the three context together,  I think it is bulk large in plants. Thank you for your fast reply.

**Comment by alexg9010** [comment]
Hi @HeChao7021,

In general, I advise running a distinct analysis for each context, since the biological implications for each one might differ. 
In addition, the cytosine positions for different contexts do not overlap, so you will not only lose information about the context but also have increased memory consumption. 

Best, 
Alex
