### ISSUE TITLE
Genome browsing from MethylDackel bedGraphCpG file

### ISSUE THREAD

**Issue by emiliomastriani** [al2na/methylKit#256]
Hello,
I used nfcore/methylseq pipeline to analyze my data and it worked well. My raw data have been obtained by affinity enrichment , binding the CpG with Human MBD2A (Not bisulfite process). I got the sorted.markDups_CpG.bedGraph file, that can be successfully imported into IGV. Now, I am in the need to identify:

1. the methylated genes
2. genomic regions (promoter, intronic, exotic, splicing site, TSS)
3. directionality (hypo/hyper methylation)

Can MethylKit be used to import the sorted.markDups_CpG.bedGraph file to retrieve the information I need?
Will MethylKit suite well to my data even if it comes from NOT bisulfite process? 
Thank you for you support.
Emilio

**Comment by alexg9010** [comment]
Hi @emiliomastriani,

I think methylKit could help with your analysis, please make sure to skim through [our vignette](https://bioconductor.org/packages/release/bioc/vignettes/methylKit/inst/doc/methylKit.html#1_Introduction) to discover how to identify what you need.  You may also ask methylKit related questions on the [methylkit discussion forum](https://groups.google.com/g/methylkit_discussion)

Concerning your questions: 

> Can MethylKit be used to import the sorted.markDups_CpG.bedGraph file to retrieve the information I need?

You should be able to directly read the bedgraph files generated with methylDackel since they are similar to the coverage files generated by Bismark [described here](https://github.com/dpryan79/MethylDackel#single-cytosine-methylation-metrics-extraction).  
To import your data please follow the [manual](https://bioconductor.org/packages/release/bioc/vignettes/methylKit/inst/doc/methylKit.html#21_Reading_the_methylation_call_files) and adjust the settings of the `methRead` function to make sure the `pipeline` receives `bismarkCoverage` and ignores the file header. 

> Will MethylKit suite well to my data even if it comes from NOT bisulfite process?

I guess there has to be a bisulfite conversion step included in the preparation of your data, otherwise, you would not be able to get meaningful results using your aforementioned analysis pipeline. However, methylKit's methods are not specifically biased towards any genome-wide (WGBS), targeted (RRBS) or affinity enriched (MBDCap, ) method to acquire your bisulfite sequencing data. 

Best
