### ISSUE TITLE
Error when running MethSeg

### ISSUE THREAD

**Issue by nnlrl** [al2na/methylKit#262]
Hello, I'm using `methylKit 1.20.0` with R4.1. When I processing some CHH context files, I used `methRead` to build the tabix index. When I used `methSeg` to segment, the following error occurred. I don't know the reason. Using the original file without tabix index did not report this error.
```
Reading context file: /path/to/file.deduped_CHH.txt.bgz
Received single location.
Performing segmentation...
Uncompressing file.
Reading file.

 *** caught segfault ***
address (nil), cause 'unknown'

Traceback:
 1: data.table::fread(file = filepath, ...)
 2: fread.gzipped(tbxFile, nrow = nrow, stringsAsFactors = FALSE,     data.table = returnDt, skip = length(Rsamtools::headerTabix(tbxFile)$header))
 3: headTabix(tbxFile = from@dbpath, nrow = from@num.records, return.type = "GRanges")
 4: asMethod(object)
 5: as(obj, "GRanges")
 6: methSeg(methRawDB, diagnostic.plot = TRUE)
An irrecoverable exception occurred. R is aborting now ...
```

**Comment by alexg9010** [comment]
Hi @nnlrl,

Based on the traceback, it seems that the error itself did not occur within `methylKit`, but was caused by reading in the data with `data.table`. Usually, a segfault indicates memory issues, thus it is interesting that the function worked with the in-memory variant as you mentioned. Since you are using the CHH methylation calls, I also assume that the files/objects are quite big given the larger number of genomic sites, again pointing toward memory as the main cause.

To mitigate the problem, but keep using the tabix indexed files, you could manually run the segmentation per chromosome, which will lead to the same results in the end, since fastseg also runs per chromosome internally.

```
tabix_path <- getDBPath(methRawDB)

## function to be passed to applyTbxByChr
methseg_fun <- function(obj) {
    ## set object names
    methylKit:::.setMethylDBNames(obj)
    ##coerce object to granges
    obj = as(obj, "GRanges")
    ## calculate methylation score
    mcols(obj)$meth = 100 * obj$numCs / obj$coverage
    ## select only required mcol
    obj = obj[, "meth"]
    res <- methylKit::methSeg(obj)
    return(data.table::as.data.table(res))
}

## run function per chromosome
methseg_byChr_dt <- methylKit:::applyTbxByChr(
    tbxFile = tabix_path,
    FUN = methseg_fun,
    return.type = "data.table"
)

## convert to GRanges and compare
meth_seg_byChr <- as(methseg_byChr_dt,"GRanges")
meth_seg_full <- methSeg(methRawDB)
```

**Comment by nnlrl** [comment]
Hi, @alexg9010 
The code is working. Thank you for taking the time to answer my questions
