### ISSUE TITLE
unite function error 

### ISSUE THREAD

**Issue by mohsennabian** [al2na/methylKit#275]
Hi, 
I am trying to get average methylation values for each exon. Running this, I get the following error. I appreciate your advice on this. 
```
exons=regionCounts(myobj,gene.obj$exons)
exons_united=unite(exons, destrand=FALSE)
```

Error: 
uniting...
Error in vecseq(f__, len__, if (allow.cartesian || notjoin || !anyDuplicated(f__,  : 
  Join results in 8406 rows; more than 7207 = nrow(x)+nrow(i). Check for duplicate key values in i each of which join to the same group in x over and over again. If that's ok, try by=.EACHI to run j for each group to avoid the large allocation. If you are sure you wish to proceed, rerun with allow.cartesian=TRUE. Otherwise, please search for this error message in the FAQ, Wiki, Stack Overflow and data.table issue tracker for advice.

**Comment by alexg9010** [comment]
Dear @mohsennabian,

I am assuming that  `myobj` is a `methylRawList` and gene.obj$exons is a GRanges, similar to the [regional analysis described in our vignette](https://bioconductor.org/packages/release/bioc/vignettes/methylKit/inst/doc/methylKit.html#41_Regional_analysis). 

The problem is that gene.obj$exons is not unique, thus we get duplicate ranges in the resulting object, leading to downstream issues when merging the methylRaw objects, causing the error that you got.

To fix this you have to make sure that the regions you are counting over with `regionCounts` are unique.
This can be achieved by simply calling `unique` on the regions. 
```
exons=regionCounts(myobj,unique(gene.obj$exons))
```

Best,
Alex
