### ISSUE TITLE
Illegal operation when opening BiocGenerics

### ISSUE THREAD

**Issue by desmodus1984** [al2na/methylKit#305]
Hi,

I am trying to run methylKit in a cluster. I was able to install methylKit but when I try loading it in R, I get the following error:

Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: BiocGenerics

Attaching package: ‘BiocGenerics’

 *** caught illegal operation ***
address 0x7fde4ea4cc8c, cause 'illegal operand'

Traceback:
 1: strsplit(x, "\n[ \t\n]*\n", perl = TRUE)
 2: lapply(strsplit(x, "\n[ \t\n]*\n", perl = TRUE), strsplit, "[ \t\n]",     perl = TRUE)
 3: strwrap(paste(same, collapse = ", "), indent = 4L, exdent = 4L)
 4: .maskedMsg(sort(conflicts[[i]]), pkg = sQuote(pkg[i]), by = cpos[i] <     lib.pos)
 5: checkConflicts(package, pkgname, pkgpath, nogenerics, ns)
 6: library(pkg, character.only = TRUE, logical.return = TRUE, lib.loc = lib.loc,     quietly = quietly)
 7: .getRequiredPackages2(pkgInfo, quietly = quietly, lib.loc = c(lib.loc,     .libPaths()))
 8: library(pkg, character.only = TRUE, logical.return = TRUE, lib.loc = lib.loc,     quietly = quietly)
 9: .getRequiredPackages2(pkgInfo, quietly = quietly, lib.loc = c(lib.loc,     .libPaths()))
10: library(methylKit)
An irrecoverable exception occurred. R is aborting now ...
/scratch/slurmd/job11049733/slurm_script: line 16: 19054 Illegal instruction     Rscript PCA.meth.R > SLURM_JOBID_NAME.out

Any suggestion on how to fix it to run on a compute node?
With 50 samples it is using ~ 200 GB of Ram, and can at most run 4 cores.
I will get soon 500 methylation samples and I will need to use a high-memory node, but as of now, I can only use the low-memory login nodes.

Thanks;

**Comment by alexg9010** [comment]
HI @desmodus1984,

This issue is unrelated to methylKit and is something that you have to fix together with your HPC provider. 

Based on googling your error it could be possible that the nodes on your cluster are using versions of OPENBLAS/BLAS libraries which are causing the crash. I found two threads with similar error messages they reported  were able to fix the problem: 
- https://groups.google.com/g/r-inla-discussion-group/c/8xctxzv4cW0
- https://bbs.archlinux.org/viewtopic.php?id=217539

Others have also reported that changing compiler flags fixed the problem:
- https://stackoverflow.com/questions/56359013/stan-code-works-fine-but-fails-on-linux-cluster

Best,
Alex

**Comment by desmodus1984** [comment]
@anthjbell which one do you think is the most likely problem in FIU HPC?
Thanks.

**Comment by desmodus1984** [comment]
The weird thing is that I can properly load it in the login node, but then in the compute node it crushes.
