### ISSUE TITLE
invalid p-values on calculateDiffMeth call

### ISSUE THREAD

**Issue by alexg9010** [al2na/methylKit#90]
https://github.com/BIMSBbioinfo/pigx_bsseq/issues/42

**Comment by katwre** [comment]
The problem is that the Fisher test can generate p-values greater than 1 due to some numerical inaccuracies (according to Bren such values that are only above 1 by an amount that is less than machine precision) and the qvalue:qvalue function shows an error when it gets as input values greater than exactly 1. I opened an issue on github qvalue package about it (https://github.com/StoreyLab/qvalue/issues/7).
